--- #YAML:1.0
name:                qn
version:             0.02
abstract:            Perl extension for quoting and splitting on newlines.
license:             ~
author:              
    - Rick Myers <jrm@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
